export const FETCH_EARTHQUAKES = 'FETCH_EARTHQUAKES'
export const FILTER_BY_MAGNITUDE = 'FILTER_BY_MAGNITUDE'
export const FILTER_BY_MAGTYPE = 'FILTER_BY_MAGTYPE'
export const RESET_FILTERS = 'RESET_FILTERS'
